#config_version=5 

switches:
    s_left_flipper:
        number:
        tags: left_flipper
    s_right_flipper:
        number:
        tags: right_flipper
    s_upper_flipper:
        number:
        tags: upper_flipper

coils:
    c_flipper_left_main:
        number:
    c_flipper_left_hold:
        number:
        allow_enable: true
    c_flipper_right_main:
        number:
    c_flipper_right_hold:
        number:
        allow_enable: true
    c_flipper_upper_main:
        number:
    c_flipper_upper_hold:
        number:
        allow_enable: true

playfields:
    playfield:
        tags: default
        default_source_device: None

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
    upper_flipper:
        main_coil: c_flipper_upper_main
        hold_coil: c_flipper_upper_hold
        activation_switch: s_upper_flipper



